spring:
  servlet:
    multipart:
      max-file-size: 5MB
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pruebaceiba
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  cloud:
    aws-s3:
      access-key: ${AWS_S3_ACCESS_KEY:aws_s3_access_key}
      secret-key: ${AWS_S3_SECRET_KEY:aws_s3_secret_key}
      client-region: ${AWS_S3_CLIENTE_REGION:us-east-2}
      bucket-name: ${AWS_S3_BUCKET_NAME:bucket_name}
